export const sampleProducts = [
  {
    name: "Elegant Rani Pink Cotton Kurti",
    category: "Kurti",
    fabric: "Cotton",
    price: 1299,
    discounted_price: 899,
    discount_percentage: 31,
    sizes: ["S", "M", "L", "XL"],
    colors: ["Rani Pink", "Royal Blue", "Emerald"],
    in_stock: true,
    rating: 4.5,
    description: "Beautiful hand-block printed cotton kurti with intricate details. Perfect for casual wear and summer festivities. Lightweight and comfortable fabric for all-day wear.",
    images: ["https://images.pexels.com/photos/8839887/pexels-photo-8839887.jpeg"]
  },
  {
    name: "Royal Blue Silk Kurta Set",
    category: "Kurta Set",
    fabric: "Silk",
    price: 2999,
    discounted_price: 2199,
    discount_percentage: 27,
    sizes: ["S", "M", "L", "XL"],
    colors: ["Royal Blue", "Maroon", "Gold"],
    in_stock: true,
    rating: 4.8,
    description: "Premium silk kurta set with matching palazzo pants. Features delicate embroidery work and comes with a dupatta. Perfect for festive occasions and celebrations.",
    images: ["https://images.pexels.com/photos/9558579/pexels-photo-9558579.jpeg"]
  },
  {
    name: "Traditional Banarasi Silk Saree",
    category: "Saree",
    fabric: "Silk",
    price: 4999,
    discounted_price: 3499,
    discount_percentage: 30,
    sizes: ["Free Size"],
    colors: ["Red", "Gold", "Maroon"],
    in_stock: true,
    rating: 4.9,
    description: "Authentic Banarasi silk saree with traditional zari work. Comes with matching blouse piece. A timeless classic that never goes out of style.",
    images: ["https://images.pexels.com/photos/3428494/pexels-photo-3428494.jpeg"]
  },
  {
    name: "Pastel Chiffon Draping Saree",
    category: "Draping Saree",
    fabric: "Chiffon",
    price: 3499,
    discounted_price: 2599,
    discount_percentage: 26,
    sizes: ["Free Size"],
    colors: ["Peach", "Mint Green", "Rose Gold"],
    in_stock: true,
    rating: 4.6,
    description: "Soft chiffon saree with pre-stitched pleats for easy draping. Lightweight and comfortable. Perfect for parties and evening events.",
    images: ["https://images.pexels.com/photos/7679454/pexels-photo-7679454.jpeg"]
  },
  {
    name: "Designer Ready-to-Wear Saree",
    category: "Ready Saree",
    fabric: "Georgette",
    price: 2799,
    discounted_price: 1999,
    discount_percentage: 29,
    sizes: ["S", "M", "L"],
    colors: ["Navy Blue", "Wine", "Emerald"],
    in_stock: true,
    rating: 4.7,
    description: "Pre-stitched ready-to-wear saree with attached blouse. Just wear it like a skirt in under 2 minutes. No draping required!",
    images: ["https://images.pexels.com/photos/8839881/pexels-photo-8839881.jpeg"]
  },
  {
    name: "Bridal Maroon Lehenga Set",
    category: "Lehenga",
    fabric: "Silk",
    price: 8999,
    discounted_price: 6499,
    discount_percentage: 28,
    sizes: ["S", "M", "L", "XL"],
    colors: ["Maroon", "Red", "Pink"],
    in_stock: true,
    rating: 5.0,
    description: "Stunning bridal lehenga with heavy embroidery and sequin work. Comes with matching choli and dupatta. Perfect for weddings and grand celebrations.",
    images: ["https://images.pexels.com/photos/8839893/pexels-photo-8839893.jpeg"]
  },
  {
    name: "Comfortable Cotton Palazzo Set",
    category: "Palazzo",
    fabric: "Cotton",
    price: 899,
    discounted_price: 649,
    discount_percentage: 28,
    sizes: ["S", "M", "L", "XL"],
    colors: ["White", "Beige", "Black"],
    in_stock: true,
    rating: 4.4,
    description: "Soft cotton palazzo pants with matching kurti. Breathable fabric perfect for daily wear. Comfortable fit with elastic waistband.",
    images: ["https://images.pexels.com/photos/6069015/pexels-photo-6069015.jpeg"]
  },
  {
    name: "Indo Western Fusion Dress",
    category: "Indo Western",
    fabric: "Viscose",
    price: 1799,
    discounted_price: 1299,
    discount_percentage: 28,
    sizes: ["S", "M", "L", "XL"],
    colors: ["Black", "Wine", "Emerald"],
    in_stock: true,
    rating: 4.5,
    description: "Modern Indo-Western dress with traditional embellishments. Perfect blend of contemporary and ethnic style. Great for parties and social events.",
    images: ["https://images.pexels.com/photos/8839895/pexels-photo-8839895.jpeg"]
  },
  {
    name: "Floral Print Linen Kurti",
    category: "Kurti",
    fabric: "Linen",
    price: 1099,
    discounted_price: 799,
    discount_percentage: 27,
    sizes: ["S", "M", "L", "XL"],
    colors: ["Yellow", "Pink", "Green"],
    in_stock: true,
    rating: 4.3,
    description: "Breezy linen kurti with beautiful floral prints. Perfect for summer wear. Comfortable and stylish for everyday use.",
    images: ["https://images.pexels.com/photos/7679426/pexels-photo-7679426.jpeg"]
  },
  {
    name: "Festive Green Georgette Kurti",
    category: "Kurti",
    fabric: "Georgette",
    price: 1499,
    discounted_price: 1099,
    discount_percentage: 27,
    sizes: ["S", "M", "L", "XL"],
    colors: ["Green", "Orange", "Purple"],
    in_stock: true,
    rating: 4.6,
    description: "Flowing georgette kurti with gold print border. Elegant and festive. Perfect for special occasions and celebrations.",
    images: ["https://images.pexels.com/photos/8839890/pexels-photo-8839890.jpeg"]
  },
  {
    name: "Premium Satin Kurta Set",
    category: "Kurta Set",
    fabric: "Satin",
    price: 2499,
    discounted_price: 1799,
    discount_percentage: 28,
    sizes: ["S", "M", "L", "XL"],
    colors: ["Silver", "Gold", "Rose Gold"],
    in_stock: true,
    rating: 4.7,
    description: "Luxurious satin kurta set with contemporary design. Includes matching dupatta and bottoms. Perfect for evening events and parties.",
    images: ["https://images.pexels.com/photos/7679462/pexels-photo-7679462.jpeg"]
  },
  {
    name: "Classic Pink Chiffon Saree",
    category: "Saree",
    fabric: "Chiffon",
    price: 2999,
    discounted_price: 2199,
    discount_percentage: 27,
    sizes: ["Free Size"],
    colors: ["Pink", "Peach", "Cream"],
    in_stock: true,
    rating: 4.8,
    description: "Elegant chiffon saree with delicate embroidery border. Lightweight and easy to drape. Perfect for formal occasions and functions.",
    images: ["https://images.pexels.com/photos/9419531/pexels-photo-9419531.jpeg"]
  }
];
